---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1l88ycpygwqhprax575gu959aes980kgvcjym7yjaqcdh5lfxcufq8pms9r
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1l88ycpygwqhprax575gu959aes980kgvcjym7yjaqcdh5lfxcufq8pms9r
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1l88ycpygwqhprax575gu959aes980kgvcjym7yjaqcdh5lfxcufq8pms9r
