---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tandoor
  namespace: housekeeping
spec:
  interval: 15m
  chart:
    spec:
      chart: tandoor
      version: 0.4.1
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: vabene1111/recipes
      tag: 1.4.5
    env:
      TIMEZONE: "${TIMEZONE}"
    envFrom:
      - secretRef:
          name: tandoor-secrets
    service:
      main:
        type: LoadBalancer
        externalIPs: ["${METALLB_TANDOOR_ADDR}"]
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:noodles
        hosts:
          - host: &host "recipes.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 8080
              - path: /static
                service:
                  port: 80
              - path: /media
                service:
                  port: 80
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        existingClaim: tandoor-config
      media:
        enabled: true
        type: pvc
        mountPath: /opt/recipes/mediafiles
        existingClaim: tandoor-media
    postgresql:
      enabled: true
      primary:
        persistence:
          enabled: true
          storageClassName: local-path
          size: 8Gi
