apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-config
  namespace: housekeeping
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-media
  namespace: housekeeping
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
