apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-secrets
    namespace: home-automation
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:BJ+rcESEL0FvlA==,iv:4k5IJkfVS5/HOlONdOg69I4F5XhyQdPwCwobWWhmvpg=,tag:9Ph7ztJCtEMysFBoWta31g==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:gRPFzYOjSvn72LPZVIM=,iv:7Kf6POjLlK76Nubc8zwvqdoTNKOupNMOu048TjxcP7A=,tag:iPkP9WIYRdNhxwyhrTHDhw==,type:str]
    HASS_LATITUDE: ENC[AES256_GCM,data:3tDLww4tCA==,iv:ENGK0d8dKzhr0jnMOuSxkZwhLrjEpCkbBr/wyj44TWE=,tag:Hr1Dtfp1oswqHElA0tIe7g==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:IYiwiQqVag==,iv:tSVe2mq1bfsxOByk9lQE+jK1G9PWBKD7i3kTAW6Ridw=,tag:c5wWPR9VpP8K26JXt+7FNg==,type:str]
    PROXY_IP: ENC[AES256_GCM,data:SYPvFl7f9hvjbpU8FA==,iv:r5gzisI12JoIEJ1TIolG4erf6Rp32AIuZtuBLBEugxU=,tag:z3BnMn3I8uHkx185qLiKNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l88ycpygwqhprax575gu959aes980kgvcjym7yjaqcdh5lfxcufq8pms9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMDRrNWEwaitiYWZWNGJB
            NXlYYkVkZlVqeU5TTkc4VWJaclVPUStGV1ZnCk8yVVVZL01ERThuSHZlaG9Mbmtl
            YmlBcTRvNk1Hb3dTdDYyNE45Wk5BZTgKLS0tIFIya0JSR0V5d0ozU3k5WGUyQU8y
            ZkZWSThUclEzTklhQnVaWlhJZXBxamcKQ5DW2XRwubm4JyMlZokl5foV8G0Z7zKr
            nDnsoN5DTZ748Oo9Eua9U719nd9EH89i1Z2Q2I6IoThSplBWXCl8Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-10T15:34:08Z"
    mac: ENC[AES256_GCM,data:a3v0NfzGBHvCb0QSjg61wRBSzPoKIeNJjYZVXAEtqmtazpqw8cvGDxJ2hJX5eX9kFgnumvc4A/aYh+ljP6wTsmVxE+x1yaKXx3DpNY265jXOcBZBPZcFccedrVALMjoSGd5dNvFkIyCZeI/O/502Hf4jaSvfgUi27gJYpRtxjTI=,iv:ONiYrP+S4XXTxmeQQuVwBcv7XMSSOaBEZ47ydQBpqvk=,tag:/eUvEyDP70jVQF5H+i/X9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
