---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app adguard-home
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: adguard/adguardhome
      tag: v0.107.35
    env:
      TZ: "${TIMEZONE}"
    args:
      - "--config"
      - "/opt/adguardhome/conf/AdGuardHome.yaml"
      - "--work-dir"
      - "/opt/adguardhome/work"
      - "--no-check-update"
    service:
      main:
        type: LoadBalancer
        externalIPs: ["${METALLB_AGH_ADDR}"]
        externalTrafficPolicy: Local
        ports:
          http:
            port: 3000
    dns:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/loadBalancerIPs: "${METALLB_AGH_ADDR}"
      ports:
        dns-tcp:
          enabled: true
          port: 53
          protocol: TCP
          targetPort: 53
        dns-udp:
          enabled: true
          port: 53
          protocol: UDP
          targetPort: 53
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:dns
        hosts:
          - host: &host "adguard.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: *app
        subPath:
          - path: conf
            mountPath: /opt/adguardhome/conf
          - path: data
            mountPath: /opt/adguardhome/work
